/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"


void
simple_nfs_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	struct OpenRequest  ropen_1_arg;
	int  *result_2;
	struct CreatRequest  rcreat_1_arg;
	struct ReadResponse  *result_3;
	struct FileAccessRequest  rread_1_arg;
	ssize_t  *result_4;
	struct FileAccessRequest  rwrite_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMPLE_NFS, DEFAULT_SIGNUM, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ropen_1(&ropen_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = rcreat_1(&rcreat_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = rread_1(&rread_1_arg, clnt);
	if (result_3 == (struct ReadResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = rwrite_1(&rwrite_1_arg, clnt);
	if (result_4 == (ssize_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	simple_nfs_1 (host);
exit (0);
}
