/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"

static CLIENT* clnt;

int* _open(struct OpenRequest* request) {
	int* result = ropen_1(request, clnt);
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return result;
}

int* _creat(struct CreatRequest* request) {
	int* result = rcreat_1(request, clnt);
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return result;
}

struct ReadResponse* _read(struct FileAccessRequest* request) {
	struct ReadResponse* result = rread_1(request, clnt);
	if (result == (struct ReadResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return result;
}

int* _write(struct FileAccessRequest* request) {
	int* result = rwrite_1(request, clnt);
	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return result;
}

int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	clnt = clnt_create (host, SIMPLE_NFS, DEFAULT_SIGNUM, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	clnt_destroy (clnt);
	exit (0);
}
